language: ruby
#bundler_args: --without development
before_install: gem update --system 1.8.25
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails23.gemfile
  - gemfiles/rails30.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails3x.gemfile
  - gemfiles/rails40.gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails23.gemfile

